Repository AlgebraicJulia/ACSets.jl, pull requests merged in 2023-10, with the labels that each got.

#54 Read acsets from Excel files
  Project.toml
  ext/ExcelACSets.jl
  src/ACSets.jl
  src/serialization/JSONACSets.jl
  src/serialization/Serialization.jl
  src/serialization/data/acset.schema.json
  test/Project.toml
  test/runtests.jl
  test/serialization/ExcelACSets.jl
  test/serialization/JSONACSets.jl
  test/serialization/Serialization.jl
  test/serialization/data/graph_one_sheet.xlsx
  test/serialization/data/mutagenesis.xlsx
Labels: enhancement

#62 Find invalid entries in homs
  src/ACSetInterface.jl
  src/DenseACSets.jl
  test/ACSets.jl
Labels: enhancement

#43 Canonical isomorph and automorphism group
  Project.toml
  ext/ACSetsnauty_jllExt.jl
  src/ACSets.jl
  src/NautyInterface.jl
  test/NautyInterface.jl
  test/Project.toml
  test/runtests.jl
Labels: enhancement, Infrastructure

#72 Don't export `generators` function
  src/NautyInterface.jl
  test/NautyInterface.jl
Labels: bug
